"""add file fields to mensajes

Revision ID: 078aef2d2cdd
Revises: 906e4c8b4686
Create Date: 2025-11-29 00:56:31.518063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '078aef2d2cdd'
down_revision: Union[str, Sequence[str], None] = '906e4c8b4686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mensajes', sa.Column('tamano_adjunto', sa.Integer(), nullable=True))
    op.add_column('mensajes', sa.Column('nombre_archivo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mensajes', 'nombre_archivo')
    op.drop_column('mensajes', 'tamano_adjunto')
    # ### end Alembic commands ###
