"""inicial_limpia

Revision ID: 906e4c8b4686
Revises: 
Create Date: 2025-11-28 17:57:36.010163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '906e4c8b4686'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codigos_otp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('codigo_hash', sa.String(length=128), nullable=False),
    sa.Column('expiracion', sa.DateTime(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=True),
    sa.Column('intentos', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_telefono', 'codigos_otp', ['telefono'], unique=False)
    op.create_table('sesiones_qr',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'confirmado', 'expirado', name='estado_qr'), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('expiracion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('apellido', sa.String(length=50), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('ultimo_estado', sa.String(length=100), nullable=True),
    sa.Column('en_linea', sa.Boolean(), nullable=True),
    sa.Column('ultima_conexion', sa.DateTime(), nullable=True),
    sa.Column('verificado', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('contactos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('contacto_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contacto_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'contacto_id', name='uq_contacto_unico')
    )
    op.create_index('ix_contactos_usuario', 'contactos', ['usuario_id'], unique=False)
    op.create_table('conversaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('es_grupo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('creador_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sesiones_web',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('token_sesion', sa.String(length=255), nullable=False),
    sa.Column('agente', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_expiracion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_sesion')
    )
    op.create_index('ix_sesion_web_usuario', 'sesiones_web', ['usuario_id'], unique=False)
    op.create_table('conversaciones_ocultas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversacion_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversacion_id', 'usuario_id', name='uq_conversacion_oculta_unica')
    )
    op.create_index('ix_conversacion_oculta_usuario', 'conversaciones_ocultas', ['usuario_id'], unique=False)
    op.create_table('llamadas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversacion_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('voz', 'video', name='tipo_llamada'), nullable=False),
    sa.Column('estado', sa.Enum('iniciada', 'finalizada', 'fallida', name='estado_llamada'), nullable=True),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('iniciada_en', sa.DateTime(), nullable=True),
    sa.Column('finalizada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversaciones.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensajes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversacion_id', sa.UUID(), nullable=False),
    sa.Column('remitente_id', sa.UUID(), nullable=True),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('url_adjunto', sa.String(length=255), nullable=True),
    sa.Column('tipo_adjunto', sa.String(length=50), nullable=True),
    sa.Column('editado_en', sa.DateTime(), nullable=True),
    sa.Column('borrado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('mensaje_id_respuesta', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversaciones.id'], ),
    sa.ForeignKeyConstraint(['mensaje_id_respuesta'], ['mensajes.id'], ),
    sa.ForeignKeyConstraint(['remitente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mensajes_conversacion_creado', 'mensajes', ['conversacion_id', 'creado_en'], unique=False)
    op.create_table('miembros_conversacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversacion_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_salida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversaciones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversacion_id', 'usuario_id', name='uq_miembro_unico')
    )
    op.create_index('ix_miembros_conversacion_conv', 'miembros_conversacion', ['conversacion_id'], unique=False)
    op.create_index('ix_miembros_conversacion_usuario_activo', 'miembros_conversacion', ['usuario_id', 'activo'], unique=False)
    op.create_table('estados_mensaje',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mensaje_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'enviado', 'entregado', 'leido', name='estado_mensaje'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mensaje_id'], ['mensajes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_estado_mensaje_mensaje', 'estados_mensaje', ['mensaje_id'], unique=False)
    op.create_table('menciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mensaje_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mensaje_id'], ['mensajes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mensaje_id', 'usuario_id', name='uq_mencion_unica')
    )
    op.create_index('ix_menciones_mensaje', 'menciones', ['mensaje_id'], unique=False)
    op.create_table('mensajes_ocultos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mensaje_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mensaje_id'], ['mensajes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mensaje_id', 'usuario_id', name='uq_mensaje_oculto_unico')
    )
    op.create_table('participantes_llamada',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('llamada_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('unido_en', sa.DateTime(), nullable=True),
    sa.Column('salido_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['llamada_id'], ['llamadas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('llamada_id', 'usuario_id', name='uq_participante_unico')
    )
    op.create_table('reacciones_mensaje',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mensaje_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('emoji', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mensaje_id'], ['mensajes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mensaje_id', 'usuario_id', name='uq_reaccion_unica')
    )
    op.create_index('ix_reacciones_mensaje_mensaje', 'reacciones_mensaje', ['mensaje_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reacciones_mensaje_mensaje', table_name='reacciones_mensaje')
    op.drop_table('reacciones_mensaje')
    op.drop_table('participantes_llamada')
    op.drop_table('mensajes_ocultos')
    op.drop_index('ix_menciones_mensaje', table_name='menciones')
    op.drop_table('menciones')
    op.drop_index('ix_estado_mensaje_mensaje', table_name='estados_mensaje')
    op.drop_table('estados_mensaje')
    op.drop_index('ix_miembros_conversacion_usuario_activo', table_name='miembros_conversacion')
    op.drop_index('ix_miembros_conversacion_conv', table_name='miembros_conversacion')
    op.drop_table('miembros_conversacion')
    op.drop_index('ix_mensajes_conversacion_creado', table_name='mensajes')
    op.drop_table('mensajes')
    op.drop_table('llamadas')
    op.drop_index('ix_conversacion_oculta_usuario', table_name='conversaciones_ocultas')
    op.drop_table('conversaciones_ocultas')
    op.drop_index('ix_sesion_web_usuario', table_name='sesiones_web')
    op.drop_table('sesiones_web')
    op.drop_table('conversaciones')
    op.drop_index('ix_contactos_usuario', table_name='contactos')
    op.drop_table('contactos')
    op.drop_table('usuarios')
    op.drop_table('sesiones_qr')
    op.drop_index('ix_otp_telefono', table_name='codigos_otp')
    op.drop_table('codigos_otp')
    # ### end Alembic commands ###
